package com.github.vaapukkax.kuphack.flagclash.sheets.widgets;

import java.util.Arrays;
import java.util.List;

import com.mojang.brigadier.exceptions.CommandSyntaxException;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.nbt.NbtList;
import net.minecraft.nbt.NbtString;
import net.minecraft.nbt.StringNbtReader;
import net.minecraft.text.Text;
import net.minecraft.util.registry.Registry;

public enum ShopLayoutItem implements Widget {

	ROOT(flag()),
	
	BLUE_KEYCARD(card(Items.BLUE_WOOL, 15)),
	PINK_KEYCARD(card(Items.PINK_WOOL, 50)),	
	GREEN_KEYCARD(card(Items.GREEN_WOOL, 45)),
	ORANGE_KEYCARD(card(Items.ORANGE_WOOL, 75)),	
	RED_KEYCARD(card(Items.RED_WOOL, 40)),
	CYAN_KEYCARD(card(Items.CYAN_WOOL, 40)),	
	WHITE_KEYCARD(card(Items.WHITE_WOOL, 50)),
	BLACK_KEYCARD(card(Items.BLACK_WOOL, 100)),
	
	SOUL_ANCHOR(nbt("{Count:1b,id:\"minecraft:soul_campfire\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Let\\'s you respawn at the fire.\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2BF9E7\",\"text\":\"Soul Anchor\"}],\"text\":\"\"}'},objectID:\"item_SoulCampfire\"}}")),
	SKULL_CRUSHER(nbt("{Count:1b,id:\"minecraft:stone_axe\",tag:{AttributeModifiers:[{Amount:-3.8d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-1570685611,-1499738244,-476127280,-1613373839]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-1691562979,1258296714,139137357,-792459702]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Woa, that\\'s one wacky axe\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 12\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 100\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 60\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Skull Crusher\"}],\"text\":\"\"}'},objectID:\"item_StoneAxe\"}}")),
	WOODEN_AXE(nbt("{Count:1b,id:\"minecraft:wooden_axe\",tag:{AttributeModifiers:[{Amount:-3.2d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;1216153196,346109862,560981195,-2061227867]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-1156711652,1272295814,-1095809377,1193129445]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" An axe to cut wood from wood\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 8\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 25\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 10\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Wooden Axe\"}],\"text\":\"\"}'},objectID:\"item_WoodenAxe\"}}")),
	HARDER_CLAY(nbt("{Count:1b,id:\"minecraft:gray_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Build a stronger house!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Harder Clay\"}],\"text\":\"\"}'},objectID:\"item_HarderClay\"}}")),
	PUFFERFISH_EGG(nbt("{Count:1b,id:\"minecraft:pufferfish_spawn_egg\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" These fishies are very puffy\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2CC048\",\"text\":\"Pufferfish Egg\"}],\"text\":\"\"}'},objectID:\"item_PufferfishEgg\"}}")),
	BELL_CLAY(nbt("{Count:1b,id:\"minecraft:yellow_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Will alert nearby players when broken\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2CC048\",\"text\":\"Bell Clay\"}],\"text\":\"\"}'},objectID:\"item_BellClay\"}}")),
	BOUNCE_CLAY(nbt("{Count:1b,id:\"minecraft:lime_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Will bounce anyone that steps on it\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2CC048\",\"text\":\"Bounce Clay\"}],\"text\":\"\"}'},objectID:\"item_BounceClay\"}}")),
	REVOKER(nbt("{Count:1b,id:\"minecraft:chiseled_polished_blackstone\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Stops anyone from placing blocks near it.\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#F7A7C2\",\"text\":\"Revoker\"}],\"text\":\"\"}'},objectID:\"item_Revoker\"}}")),
	SHARPENED_PICKAXE(nbt("{Count:1b,id:\"minecraft:stone_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-796671423,383475313,782893626,569461128]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-674995289,-1089381216,-546208278,1287767779]}],Damage:0,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}],HideFlags:127,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Slick sharp pickaxe with increased efficiency\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 10\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 10\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Sharpened Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_SharpenedPickaxe\"}}")),
	CHEAPER_HARDEST_CLAY(nbt("{Count:1b,id:\"minecraft:black_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Build the strongest house, Now 90% off!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Cheaper Hardest Clay\"}],\"text\":\"\"}'},objectID:\"item_CheaperHardestClay\"}}")),
	HARDEST_CLAY(nbt("{Count:1b,id:\"minecraft:black_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Build the strongest house!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Hardest Clay\"}],\"text\":\"\"}'},objectID:\"item_HardestClay\"}}")),
	LEATHER_BOOTS(nbt("{Count:1b,id:\"minecraft:leather_boots\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-348313749,-706652158,338585354,-717600870]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Toe protecters\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 3\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Leather Boots\"}],\"text\":\"\"}'},objectID:\"item_LeatherBoots\"}}")),
	LEATHER_LEGGINGS(nbt("{Count:1b,id:\"minecraft:leather_leggings\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-187227765,938918778,-411323933,49409105]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Finally.. Pants!\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 5\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Leather Leggings\"}],\"text\":\"\"}'},objectID:\"item_LeatherLeggings\"}}")),
	IRON_AXE(nbt("{Count:1b,id:\"minecraft:iron_axe\",tag:{AttributeModifiers:[{Amount:-3.2d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;946651025,-905211735,584251434,-1175723727]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-1227180480,-1240650942,552894963,126456503]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" An axe to cut wood from wood\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 12\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 25\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 12\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Iron Axe\"}],\"text\":\"\"}'},objectID:\"item_IronAxe\"}}")),
	CHAINMAIL_BOOTS(nbt("{Count:1b,id:\"minecraft:chainmail_boots\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-1751801985,1038210754,124085750,-1204734429]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Basically see though socks.\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 5\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Chainmail Boots\"}],\"text\":\"\"}'},objectID:\"item_ChainmailBoots\"}}")),
	SHATTERKELP(nbt("{Count:1b,id:\"minecraft:dried_kelp_block\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Shatters when broken!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#FF4040\",\"text\":\"Shatterkelp\"}],\"text\":\"\"}'},objectID:\"item_Shatterkelp\"}}")),
	RED_SOUP(nbt("{Count:1b,id:\"minecraft:beetroot_soup\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Ooo yummy! \"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"},{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\"Grants regeneration for a short period\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#FF4040\",\"text\":\"Red Soup\"}],\"text\":\"\"}'},objectID:\"item_BloodSoup\"}}")),
	SHROOMLIGHT(nbt("{Count:1b,id:\"minecraft:shroomlight\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Light up your day!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2BF9E7\",\"text\":\"Shroomlight\"}],\"text\":\"\"}'},objectID:\"item_Shroomlight\"}}")),
	RELOCATION_WAND(nbt("{Count:1b,id:\"minecraft:compass\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Teleports you to your flag or to spawn\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Relocation Wand\"}],\"text\":\"\"}'},objectID:\"item_RelocationWand\"}}")),
	THROWABLE_TNT(nbt("{Count:1b,id:\"minecraft:tnt\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Kaboom!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Throwable TNT\"}],\"text\":\"\"}'},objectID:\"item_Tnt\"}}")),
	CHAINMAIL_PANTS(nbt("{Count:1b,id:\"minecraft:chainmail_leggings\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-1128946059,-2799406,937002379,-321974061]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Gotta protect that booty!\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 8\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#3A61FF\",\"text\":\"Chainmail Pants\"}],\"text\":\"\"}'},objectID:\"item_ChainmailLeggings\"}}")),
	SHADE_SHARD(nbt("{Count:1b,id:\"minecraft:flint\",tag:{Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Launches you backwards\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2CC048\",\"text\":\"Shade Shard\"}],\"text\":\"\"}'},objectID:\"item_ShadeShard\"}}")),
	LIFE_ANCHOR(nbt("{Count:1b,id:\"minecraft:campfire\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Heals you over time when you are nearby!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#FF4040\",\"text\":\"Life Anchor\"}],\"text\":\"\"}'},objectID:\"item_Campfire\"}}")),
	SOOTHING_CLAY(nbt("{Count:1b,id:\"minecraft:pink_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Let\\'s you focus faster when standing on it.\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#F7A7C2\",\"text\":\"Soothing Clay\"}],\"text\":\"\"}'},objectID:\"item_SoothingClay\"}}")),
	HARDWOOD_BOW(nbt("{Count:1b,id:\"minecraft:bow\",tag:{Damage:0,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 13\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" \"},{\"bold\":true,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\"⏏\"},{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 25\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2CC048\",\"text\":\"Hardwood Bow\"}],\"text\":\"\"}'},objectID:\"item_Hardwoodbow\"}}")),
	POWERED_IRON_PICKAXE(nbt("{Count:1b,id:\"minecraft:iron_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-1571592179,-968186624,-849517979,1451358064]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;1398628293,1092120631,580555326,-1885826087]}],Damage:0,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}],HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" A buffed up iron pick\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 10\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 18\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Iron Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_PoweredIronPickaxe\"}}")),
	ENDER_PEARL(nbt("{Count:1b,id:\"minecraft:ender_pearl\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Teleport a short distance away!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2BF9E7\",\"text\":\"Ender Pearl\"}],\"text\":\"\"}'},objectID:\"item_EnderPearl\"}}")),
	TURRET_BONE(nbt("{Count:1b,id:\"minecraft:bone\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Let\\'s you summon a turret\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2BF9E7\",\"text\":\"Turret Bone\"}],\"text\":\"\"}'},objectID:\"item_TurretBone\"}}")),
	ANCHORING_CLAY(nbt("{Count:1b,id:\"minecraft:cyan_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Will anchor someone when they break it\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\"Anchoring Clay\"}],\"text\":\"\"}'},objectID:\"item_AnchoringClay\"}}")),
	CHICKEN_WING(nbt("{Count:1b,id:\"minecraft:feather\",tag:{Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Launches you forwards\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#2CC048\",\"text\":\"Chicken Wing\"}],\"text\":\"\"}'},objectID:\"item_ChickenWing\"}}")),
	LEATHER_TUNIC(nbt("{Count:1b,id:\"minecraft:leather_chestplate\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;1122307725,-1206155872,-541580146,-1093397020]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Some clothes would be nice..\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 6\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Leather Tunic\"}],\"text\":\"\"}'},objectID:\"item_LeatherTunic\"}}")),
	CHAINMAIL_CHESTPLATE(nbt("{Count:1b,id:\"minecraft:chainmail_chestplate\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-1884271619,-194824420,-1909694386,-478323659]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Mid.\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 8\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Chainmail Chestplate\"}],\"text\":\"\"}'},objectID:\"item_ChainmailChestplate\"}}")),
	IRON_BREASTPLATE(nbt("{Count:1b,id:\"minecraft:iron_chestplate\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;274754263,476548046,1449121207,394659563]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" A knight would wear this\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 10\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Iron Breastplate\"}],\"text\":\"\"}'},objectID:\"item_IronChestplate\"}}")),
	DIAMOND_CHESTPLATE(nbt("{Count:1b,id:\"minecraft:diamond_chestplate\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-351374610,-1553192721,985594415,-806201766]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Fashionable!\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 12\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Diamond Chestplate\"}],\"text\":\"\"}'},objectID:\"item_DiamondChestplate\"}}")),
	WOODEN_SWORD(nbt("{Count:1b,id:\"minecraft:wooden_sword\",tag:{AttributeModifiers:[{Amount:99995.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-107158106,565936753,-886463878,-298877881]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-2097088473,-1491474649,407304431,-1605367294]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" A very basic sword, \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" It isn\\'t really meant to be used in real combat\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 16\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 0\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 5\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Wooden Sword\"}],\"text\":\"\"}'},objectID:\"item_WoodenSword\"}}")),
	GOLDEN_HARNESS(nbt("{Count:1b,id:\"minecraft:golden_chestplate\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.armor\",Name:\"generic.armor\",Operation:0,Slot:\"mainhand\",UUID:[I;-1560398823,-1298490704,-470559717,304624180]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" The power of gold protects your soul\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🛡 14\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Golden Harness\"}],\"text\":\"\"}'},objectID:\"item_GoldenChestplate\"}}")),
	STONE_SWORD(nbt("{Count:1b,id:\"minecraft:stone_sword\",tag:{AttributeModifiers:[{Amount:99995.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-2059107946,-88182736,609257616,999694726]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;895581241,-324318291,186350786,-1635133747]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Smells like stone\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 18\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 0\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 6\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Stone Sword\"}],\"text\":\"\"}'},objectID:\"item_StoneSword\"}}")),
	IRON_SWORD(nbt("{Count:1b,id:\"minecraft:iron_sword\",tag:{AttributeModifiers:[{Amount:99995.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-1847519598,1473929426,-425883759,-1854158456]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-397926763,-453569477,-1713485248,530623721]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" A pretty nice sword\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 21\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 0\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 7\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Iron Sword\"}],\"text\":\"\"}'},objectID:\"item_IronSword\"}}")),
	WOODEN_PICKAXE(nbt("{Count:1b,id:\"minecraft:wooden_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-1832627734,1236423582,-645910757,1401231831]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;396876639,-1022275116,180924651,-913797308]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Very basic pickaxe\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 10\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 12\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Wooden Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_WoodenPickaxe\"}}")),
	DIAMOND_SWORD(nbt("{Count:1b,id:\"minecraft:diamond_sword\",tag:{AttributeModifiers:[{Amount:99995.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-1400127333,1469241802,556640553,-302451488]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;1245603707,-2105839184,-2017581769,1272956104]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Shiny sparkles!\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 24\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 0\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 8\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Diamond Sword\"}],\"text\":\"\"}'},objectID:\"item_DiamondSword\"}}")),
	STONE_PICKAXE(nbt("{Count:1b,id:\"minecraft:stone_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-2039387835,-1309498711,-198986348,-203166522]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;59278234,-1502991504,-1454425131,-375718861]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" For crushing rocks, and people\\'s dreams\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 10\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 15\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Stone Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_StonePickaxe\"}}")),
	GOLDEN_SWORD(nbt("{Count:1b,id:\"minecraft:golden_sword\",tag:{AttributeModifiers:[{Amount:99995.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;111028536,440428980,1133017079,1140499815]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;924846990,921050098,-670900412,563105954]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" The ultimate sword!\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 26\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 0\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 9\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Golden Sword\"}],\"text\":\"\"}'},objectID:\"item_GoldenSword\"}}")),
	IRON_PICKAXE(nbt("{Count:1b,id:\"minecraft:iron_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;451889959,638948544,-1262074113,-277116125]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-1275661625,-654168496,390302198,-464574663]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" A very neato pickaxe\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 10\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 18\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Iron Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_IronPickaxe\"}}")),
	DIAMOND_PICKAXE(nbt("{Count:1b,id:\"minecraft:diamond_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-758701311,385340073,-1803770921,1038058715]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;-1326002828,1394814862,602544548,709637382]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Cabon-based destruction\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 10\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 21\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Diamond Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_DiamondPickaxe\"}}")),
	GOLDEN_PICKAXE(nbt("{Count:1b,id:\"minecraft:golden_pickaxe\",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:\"minecraft:generic.attack_speed\",Name:\"generic.attack_speed\",Operation:0,Slot:\"mainhand\",UUID:[I;-947864524,-1797917412,-1942765961,1368462843]},{Amount:10.0d,AttributeName:\"minecraft:generic.attack_damage\",Name:\"generic.attack_damage\",Operation:0,Slot:\"mainhand\",UUID:[I;484560383,230909076,-1999707766,994601136]}],Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" The (totally) best pickaxe!\"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" 🗡 15\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⌚ 5\"}],\"text\":\"\"}','{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#E4E3EE\",\"text\":\" ⭐ 25\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Golden Pickaxe\"}],\"text\":\"\"}'},objectID:\"item_GoldenPickaxe\"}}")),
	HARD_CLAY(nbt("{Count:1b,id:\"minecraft:brown_terracotta\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Build a house!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Hard Clay\"}],\"text\":\"\"}'},objectID:\"item_HardClay\"}}")),
	BLASTPROOF_GLASS(nbt("{Count:1b,id:\"minecraft:glass\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Protect your base from the explodies!\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Blastproof Glass\"}],\"text\":\"\"}'},objectID:\"item_BlastproofGlass\"}}")),
	HOOKSHOOT_HOOK(nbt("{Count:1b,id:\"minecraft:target\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Can ya hook me up?\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Hookshot Hook\"}],\"text\":\"\"}'},objectID:\"item_HookshotHook\"}}")),
	GLASS_BOTTLE(nbt("{Count:1b,id:\"minecraft:glass_bottle\",tag:{display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" A bottle that can be filled with various liquids\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#B4CAF9\",\"text\":\"Glass Bottle\"}],\"text\":\"\"}'},objectID:\"item_Bottle\"}}")),
	HOOKSHOOT(nbt("{Count:1b,id:\"minecraft:golden_hoe\",tag:{Damage:0,HideFlags:255,Unbreakable:1b,display:{Lore:['{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\" Let\\'s you hook onto things far away. \"}],\"text\":\"\"}','{\"extra\":[{\"text\":\" \"},{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5C60A3\",\"text\":\"Try it on some haybales\"}],\"text\":\"\"}'],Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"#5E46BF\",\"text\":\"Hookshot\"}],\"text\":\"\"}'},objectID:\"item_Hookshot\"}}"));
	
	private final ItemStack stack;
	
	private ShopLayoutItem(ItemStack stack) {
		this.stack = stack;
	}
	
	@Override
	public ItemStack getIcon() {
		return this.stack;
	}
	
	@Override
	public String toString() {
		String name = this.stack.getName().getString();
		if (name.equals("minecraft")) return this.stack.getItem().getName(stack).getString();
		return name;
	}
	
	private static ItemStack card(Item item, int tokens) {
		ItemStack stack = new ItemStack(item);
		stack.setCustomName(Text.literal(Registry.ITEM.getId(item).getNamespace()));
		setLore(stack, Arrays.asList("§3Token: "+tokens));
		return stack;
	}
	
	private static ItemStack flag() {
		ItemStack stack = new ItemStack(Items.RED_BANNER);
		stack.setCustomName(Text.literal("Root"));
		return stack;
	}
	
	private static ItemStack nbt(String nbt) {
		try {
			return ItemStack.fromNbt(StringNbtReader.parse(nbt));
		} catch (CommandSyntaxException e) {
			throw new IllegalArgumentException("Invalid NBT: "+e+" ("+nbt+")");
		}
	}
	
	private static void setLore(ItemStack stack, List<String> lore) {
		NbtList loreTag = new NbtList();
		lore.forEach(line -> loreTag.add(NbtString.of(Text.Serializer.toJson(Text.literal(line)))));
		stack.getOrCreateSubNbt(ItemStack.DISPLAY_KEY).put(ItemStack.LORE_KEY, loreTag);
	}

}
